language: generic

services:
 - docker

jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y sshpass

addons:
  - ssh_known_hosts: 68.183.72.62

env:
  global:
    - version=0.1.0
    - date=$(date +%Y%m%d-%H%M%S)
    - dockerrepo=klibio/io.klib.docker.osgi.tutorial
    - commit=`echo "$TRAVIS_COMMIT"|cut -c1-7`
    - dockerversion=${version}.${date}_${commit}
    
cache:
  directories:
  - $HOME/.m2

before_script:
  - unset _JAVA_OPTIONS

script: 
#javabuild
  - mvn verify -f ./quickstart/
  - docker build -t $dockerrepo:${TRAVIS_BRANCH}-$dockerversion -t $dockerrepo:${TRAVIS_BRANCH}-latest --file ./Dockerfile-alpine.osgi.txt . 
#dockerpush
  - docker login -u $DCKUSR -p $DCKPW
  - docker push $dockerrepo:${TRAVIS_BRANCH}-$dockerversion
  - docker push $dockerrepo:${TRAVIS_BRANCH}-latest
#digitaloceandeploy
  - sshpass -p ${SSHPH} ssh root@${IP}
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker pull $dockerrepo:${TRAVIS_BRANCH}-latest
  - docker container run -d -p 8888:8080 $dockerrepo:${TRAVIS_BRANCH}-latest
  - exit

