language: generic
services:
- docker
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv
  -in travis_rsa.enc -out /tmp/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_rsa
- ssh-add /tmp/travis_rsa
env:
  global:
  - version=0.1.0
  - date=$(date +%Y%m%d-%H%M%S)
  - dockerrepo=klibio/io.klib.docker.osgi.tutorial
  - commit=`echo "$TRAVIS_COMMIT"|cut -c1-7`
  - dockerversion=${version}.${date}_${commit}
  - containerids=$(docker ps -a -q --filter ancestor=$dockerrepo:${TRAVIS_BRANCH}-latest)
cache:
  directories:
  - "$HOME/.m2"
before_script:
- unset _JAVA_OPTIONS
script:
#build quickstart applet and docker image
- mvn verify -f ./quickstart/
- docker build -t $dockerrepo:${TRAVIS_BRANCH}-$dockerversion -t $dockerrepo:${TRAVIS_BRANCH}-latest
  --file ./Dockerfile-alpine.osgi.txt .
#push docker image
- docker login -u $DCKUSR -p $DCKPW
- docker push $dockerrepo:${TRAVIS_BRANCH}-$dockerversion
- docker push $dockerrepo:${TRAVIS_BRANCH}-latest
#add droplet to known hosts and update container ran on droplet when pushed to master
- ssh-keyscan -t rsa ${IP} >> $HOME/.ssh/known_hosts
- echo "${containerids} && docker rm -f ${containerids}; docker pull $dockerrepo:${TRAVIS_BRANCH}-latest && docker container run -d -p 8889:8080 $dockerrepo:${TRAVIS_BRANCH}-latest" | ssh root@${IP}
#- echo "docker rm -f ${containerids}; docker pull $dockerrepo:${TRAVIS_BRANCH}-latest && docker container run -d -p 8888:8080 $dockerrepo:${TRAVIS_BRANCH}-latest" | ssh root@${IP};
#- if [ "$TRAVIS_BRANCH" = "develop" ]; then echo "docker rm -f ${containerids}; docker pull $dockerrepo:${TRAVIS_BRANCH}-latest && docker container run -d -p 8889:8080 $dockerrepo:${TRAVIS_BRANCH}-latest" | ssh root@${IP}; fi
#- if [ "$TRAVIS_BRANCH" = "master" ]; then echo "docker rm -f ${containerids}; docker pull $dockerrepo:${TRAVIS_BRANCH}-latest && docker container run -d -p 8888:8080 $dockerrepo:${TRAVIS_BRANCH}-latest" | ssh root@${IP}; fi
