FROM openjdk:8-alpine

ECHO \# DEBUGGING INFO
SET
ECHO \# DEBUGGING INFO
PWD
ECHO

RUN mkdir -p /usr/src/app
COPY quickstart/app/target/app.jar /usr/src/app
WORKDIR /usr/src/app
CMD java -jar app.jar
